# Generated by Django 2.2.4 on 2019-08-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='main',
            fields=[
                ('adID', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('adType', models.CharField(max_length=10, null=True)),
                ('condition', models.CharField(max_length=10, null=True)),
                ('make', models.CharField(max_length=20, null=True)),
                ('model', models.CharField(max_length=25, null=True)),
                ('price', models.IntegerField(null=True)),
                ('province', models.CharField(max_length=2, null=True)),
                ('city', models.CharField(max_length=15, null=True)),
                ('year', models.CharField(max_length=4, null=True)),
                ('kilometers', models.CharField(max_length=11, null=True)),
                ('exterior_color', models.CharField(max_length=15, null=True)),
                ('fuel_type', models.CharField(max_length=20, null=True)),
                ('body_type', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='time',
            fields=[
                ('adID', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('time_entered', models.DateField(null=True)),
                ('time_updated', models.DateField(null=True)),
            ],
        ),
    ]
