# Generated by Django 2.2.4 on 2019-08-29 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='main',
            table='main',
        ),
        migrations.AlterModelTable(
            name='time',
            table='time',
        ),
    ]
