# Generated by Django 2.2.4 on 2019-09-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_auto_20190829_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='fuel_type',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
