# Generated by Django 2.2.4 on 2019-09-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_auto_20190901_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='kilometers',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
