# Generated by Django 2.2.4 on 2019-09-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_auto_20190901_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='body_type',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
