# Generated by Django 2.2.4 on 2019-10-19 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0006_vehicle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='full_vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboards.vehicle_image'),
        ),
    ]
