# Generated by Django 2.2.4 on 2019-10-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0008_auto_20191019_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_image',
            name='image_path',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
