# Generated by Django 2.2.4 on 2019-11-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0009_auto_20191019_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='full_vehicle',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
