# Generated by Django 2.2.4 on 2019-12-15 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0010_auto_20191124_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='time_entered',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='time_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
